[package]
name = "munode-protocol"
version.workspace = true
edition.workspace = true

[dependencies]
prost = { workspace = true }
bytes = { workspace = true }
thiserror = { workspace = true }
num_enum = { workspace = true }
aes = { workspace = true }
ring = { workspace = true }

[build-dependencies]
prost-build = { workspace = true }
