[package]
name = "munode-common"
version.workspace = true
edition.workspace = true

[dependencies]
munode-protocol = { workspace = true }
tokio = { workspace = true }
serde = { workspace = true }
toml = { workspace = true }
serde_json = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
thiserror = { workspace = true }
anyhow = { workspace = true }
