/// Test user definitions — mirrors `tests/integration/test-users.ts`.

#[derive(Debug, Clone)]
pub struct TestUser {
    pub username: &'static str,
    pub password: &'static str,
    pub user_id: u32,
    pub groups: &'static [&'static str],
}

/// All test users available in the auth service.
pub const TEST_USERS: &[TestUser] = &[
    TestUser {
        username: "admin",
        password: "admin123",
        user_id: 1,
        groups: &["admin"],
    },
    TestUser {
        username: "user1",
        password: "password1",
        user_id: 2,
        groups: &["user"],
    },
    TestUser {
        username: "user2",
        password: "password2",
        user_id: 3,
        groups: &["user"],
    },
    TestUser {
        username: "guest",
        password: "guest123",
        user_id: 4,
        groups: &["user"],
    },
    TestUser {
        username: "user3",
        password: "password3",
        user_id: 5,
        groups: &["user"],
    },
    TestUser {
        username: "user5",
        password: "password5",
        user_id: 7,
        groups: &["user"],
    },
    TestUser {
        username: "admin_password",
        password: "admin_password",
        user_id: 11,
        groups: &["admin"],
    },
    TestUser {
        username: "ninja_user1",
        password: "ninja_password",
        user_id: 15,
        groups: &["ninja"],
    },
    TestUser {
        username: "ninja_user2",
        password: "ninja_password",
        user_id: 16,
        groups: &["ninja"],
    },
    TestUser {
        username: "ninja_cross",
        password: "ninja_password",
        user_id: 17,
        groups: &["ninja"],
    },
    TestUser {
        username: "user_state",
        password: "user_password",
        user_id: 18,
        groups: &["user"],
    },
    TestUser {
        username: "user_cross1",
        password: "user_password",
        user_id: 19,
        groups: &["user"],
    },
    TestUser {
        username: "user_cross2",
        password: "user_password",
        user_id: 20,
        groups: &["user"],
    },
    TestUser {
        username: "user_edge1",
        password: "user_password",
        user_id: 21,
        groups: &["user"],
    },
    TestUser {
        username: "user_edge2",
        password: "user_password",
        user_id: 22,
        groups: &["user"],
    },
    TestUser {
        username: "sender_edge1",
        password: "password1",
        user_id: 23,
        groups: &["user"],
    },
    TestUser {
        username: "sender_edge2",
        password: "password1",
        user_id: 24,
        groups: &["user"],
    },
    TestUser {
        username: "receiver1",
        password: "password1",
        user_id: 25,
        groups: &["user"],
    },
    TestUser {
        username: "receiver2",
        password: "password2",
        user_id: 26,
        groups: &["user"],
    },
    TestUser {
        username: "poor_direct_sender",
        password: "pass1",
        user_id: 27,
        groups: &["user"],
    },
    TestUser {
        username: "poor_direct_receiver",
        password: "pass3",
        user_id: 28,
        groups: &["user"],
    },
    TestUser {
        username: "balance_sender",
        password: "pass1",
        user_id: 29,
        groups: &["user"],
    },
    TestUser {
        username: "balance_receiver",
        password: "pass4",
        user_id: 30,
        groups: &["user"],
    },
    TestUser {
        username: "moderator",
        password: "mod123",
        user_id: 92,
        groups: &["moderator"],
    },
    // ACL operations integration tests.
    TestUser {
        username: "acl_op_user",
        password: "acl_op_pass",
        user_id: 750,
        groups: &["user", "acl_testers"],
    },
    TestUser {
        username: "acl_op_observer",
        password: "acl_op_obs_pass",
        user_id: 751,
        groups: &["user", "acl_testers"],
    },
    TestUser {
        username: "voice_sender",
        password: "pass1",
        user_id: 101,
        groups: &["user"],
    },
    TestUser {
        username: "voice_recv_e1_same",
        password: "pass2",
        user_id: 102,
        groups: &["user"],
    },
    TestUser {
        username: "voice_recv_e2_same",
        password: "pass3",
        user_id: 103,
        groups: &["user"],
    },
    TestUser {
        username: "udp_test_user1",
        password: "password123",
        user_id: 201,
        groups: &["user"],
    },
    TestUser {
        username: "udp_sender",
        password: "password123",
        user_id: 202,
        groups: &["user"],
    },
    TestUser {
        username: "udp_receiver",
        password: "password123",
        user_id: 203,
        groups: &["user"],
    },
    TestUser {
        username: "routing_config_test",
        password: "pass1",
        user_id: 301,
        groups: &["user"],
    },
    TestUser {
        username: "rtt_sender",
        password: "pass1",
        user_id: 302,
        groups: &["user"],
    },
    TestUser {
        username: "rtt_receiver",
        password: "pass2",
        user_id: 303,
        groups: &["user"],
    },
    TestUser {
        username: "loss_sender",
        password: "pass1",
        user_id: 304,
        groups: &["user"],
    },
    TestUser {
        username: "loss_receiver",
        password: "pass2",
        user_id: 305,
        groups: &["user"],
    },
    TestUser {
        username: "direct_sender",
        password: "pass1",
        user_id: 306,
        groups: &["user"],
    },
    TestUser {
        username: "direct_receiver",
        password: "pass2",
        user_id: 307,
        groups: &["user"],
    },
    TestUser {
        username: "tcp_fallback_sender",
        password: "pass1",
        user_id: 308,
        groups: &["user"],
    },
    TestUser {
        username: "tcp_fallback_receiver",
        password: "pass2",
        user_id: 309,
        groups: &["user"],
    },
    TestUser {
        username: "route_table_test",
        password: "pass1",
        user_id: 310,
        groups: &["user"],
    },
    TestUser {
        username: "cross_edge_sender",
        password: "pass1",
        user_id: 311,
        groups: &["user"],
    },
    TestUser {
        username: "cross_edge_receiver",
        password: "pass2",
        user_id: 312,
        groups: &["user"],
    },
    TestUser {
        username: "deaf_test_sender",
        password: "pass1",
        user_id: 313,
        groups: &["user"],
    },
    TestUser {
        username: "deaf_test_deaf",
        password: "pass2",
        user_id: 314,
        groups: &["user"],
    },
    TestUser {
        username: "deaf_test_normal",
        password: "pass3",
        user_id: 315,
        groups: &["user"],
    },
    TestUser {
        username: "hub_bypass_sender",
        password: "pass1",
        user_id: 316,
        groups: &["user"],
    },
    TestUser {
        username: "hub_bypass_receiver",
        password: "pass2",
        user_id: 317,
        groups: &["user"],
    },
    TestUser {
        username: "relay_compute_user",
        password: "pass1",
        user_id: 318,
        groups: &["user"],
    },
    TestUser {
        username: "route_push_user",
        password: "pass1",
        user_id: 319,
        groups: &["user"],
    },
    TestUser {
        username: "relay_sender",
        password: "pass1",
        user_id: 320,
        groups: &["user"],
    },
    TestUser {
        username: "relay_receiver",
        password: "pass2",
        user_id: 321,
        groups: &["user"],
    },
    TestUser {
        username: "stress_sender",
        password: "pass1",
        user_id: 322,
        groups: &["user"],
    },
    TestUser {
        username: "stress_receiver",
        password: "pass2",
        user_id: 323,
        groups: &["user"],
    },
    TestUser {
        username: "quality_test_e1",
        password: "pass1",
        user_id: 324,
        groups: &["user"],
    },
    TestUser {
        username: "quality_test_e2",
        password: "pass2",
        user_id: 325,
        groups: &["user"],
    },
    TestUser {
        username: "quality_test_e3",
        password: "pass3",
        user_id: 326,
        groups: &["user"],
    },
    TestUser {
        username: "quality_test_e4",
        password: "pass4",
        user_id: 327,
        groups: &["user"],
    },
    TestUser {
        username: "relay_sender_e1",
        password: "pass1",
        user_id: 328,
        groups: &["user"],
    },
    TestUser {
        username: "relay_receiver_e4",
        password: "pass2",
        user_id: 329,
        groups: &["user"],
    },
    TestUser {
        username: "intermediate_e2",
        password: "pass2",
        user_id: 330,
        groups: &["user"],
    },
    TestUser {
        username: "intermediate_e3",
        password: "pass3",
        user_id: 331,
        groups: &["user"],
    },
    TestUser {
        username: "multi_edge_e1",
        password: "pass1",
        user_id: 401,
        groups: &["user"],
    },
    TestUser {
        username: "multi_edge_e2",
        password: "pass2",
        user_id: 402,
        groups: &["user"],
    },
    TestUser {
        username: "multi_edge_e3",
        password: "pass3",
        user_id: 403,
        groups: &["user"],
    },
    TestUser {
        username: "multi_edge_e4",
        password: "pass4",
        user_id: 404,
        groups: &["user"],
    },
    TestUser {
        username: "broadcast_sender",
        password: "pass1",
        user_id: 405,
        groups: &["user"],
    },
    TestUser {
        username: "broadcast_e1",
        password: "pass1",
        user_id: 406,
        groups: &["user"],
    },
    TestUser {
        username: "broadcast_e2",
        password: "pass2",
        user_id: 407,
        groups: &["user"],
    },
    TestUser {
        username: "broadcast_e3",
        password: "pass3",
        user_id: 408,
        groups: &["user"],
    },
    TestUser {
        username: "broadcast_e4",
        password: "pass4",
        user_id: 409,
        groups: &["user"],
    },
    TestUser {
        username: "degradation_sender",
        password: "pass1",
        user_id: 501,
        groups: &["user"],
    },
    TestUser {
        username: "degradation_receiver",
        password: "pass2",
        user_id: 502,
        groups: &["user"],
    },
    TestUser {
        username: "severe_sender",
        password: "pass1",
        user_id: 503,
        groups: &["user"],
    },
    TestUser {
        username: "severe_receiver",
        password: "pass2",
        user_id: 504,
        groups: &["user"],
    },
    TestUser {
        username: "recovery_sender",
        password: "pass1",
        user_id: 505,
        groups: &["user"],
    },
    TestUser {
        username: "recovery_receiver",
        password: "pass2",
        user_id: 506,
        groups: &["user"],
    },
    TestUser {
        username: "network_sim_sender",
        password: "pass1",
        user_id: 507,
        groups: &["user"],
    },
    TestUser {
        username: "network_sim_receiver",
        password: "pass2",
        user_id: 508,
        groups: &["user"],
    },
    TestUser {
        username: "packet_loss_sender",
        password: "pass1",
        user_id: 509,
        groups: &["user"],
    },
    TestUser {
        username: "packet_loss_receiver",
        password: "pass2",
        user_id: 510,
        groups: &["user"],
    },
    TestUser {
        username: "random_payload_user",
        password: "random_pass",
        user_id: 511,
        groups: &["user"],
    },
    TestUser {
        username: "random_receiver",
        password: "pass1",
        user_id: 512,
        groups: &["user"],
    },
    TestUser {
        username: "multi_hop_sender",
        password: "pass1",
        user_id: 513,
        groups: &["user"],
    },
    TestUser {
        username: "multi_hop_receiver",
        password: "pass2",
        user_id: 514,
        groups: &["user"],
    },
    TestUser {
        username: "relay_test_e2",
        password: "pass3",
        user_id: 515,
        groups: &["user"],
    },
    TestUser {
        username: "relay_test_e3",
        password: "pass4",
        user_id: 516,
        groups: &["user"],
    },
];

pub fn find_user(username: &str) -> Option<&'static TestUser> {
    TEST_USERS.iter().find(|u| u.username == username)
}
