/**
 * 测试用户配置
 * 包含所有测试中使用的用户及其密码映射
 */

export const testUserPasswords: Record<string, { password: string; user_id: number; groups?: string[] }> = {
      'admin': { password: 'admin123', user_id: 1, groups: ['admin'] },
      'admin_password': { password: 'admin_password', user_id: 11, groups: ['admin'] },
      'user1': { password: 'password1', user_id: 2 },
      'user2': { password: 'password2', user_id: 3 },
      'guest': { password: 'guest123', user_id: 4 },
      'ninja_user1': { password: 'ninja_password', user_id: 15, groups: ['ninja'] },
      'ninja_user2': { password: 'ninja_password', user_id: 16, groups: ['ninja'] },
      'ninja_cross': { password: 'ninja_password', user_id: 17, groups: ['ninja'] },
      'user_state': { password: 'user_password', user_id: 18 },
      'user_cross1': { password: 'user_password', user_id: 19 },
      'user_cross2': { password: 'user_password', user_id: 20 },
      // User visibility test users
      'user_edge1': { password: 'user_password', user_id: 21 },
      'user_edge2': { password: 'user_password', user_id: 22 },
      'sender_edge1': { password: 'password1', user_id: 23 },
      'sender_edge2': { password: 'password1', user_id: 24 },
      'receiver1': { password: 'password1', user_id: 25 },
      'receiver2': { password: 'password2', user_id: 26 },
      // UDP quality simulation test users
      'poor_direct_sender': { password: 'pass1', user_id: 27 },
      'poor_direct_receiver': { password: 'pass3', user_id: 28 },
      'balance_sender': { password: 'pass1', user_id: 29 },
      'balance_receiver': { password: 'pass4', user_id: 30 },
      'moderator': { password: 'mod123', user_id: 92, groups: ['moderator'] },
      // Voice test users
      'voice_sender': { password: 'pass1', user_id: 101 },
      'voice_recv_e1_same': { password: 'pass2', user_id: 102 },
      'voice_recv_e2_same': { password: 'pass3', user_id: 103 },
      // UDP test users
      'udp_test_user1': { password: 'password123', user_id: 201 },
      'udp_sender': { password: 'password123', user_id: 202 },
      'udp_receiver': { password: 'password123', user_id: 203 },
      // Voice routing test users
      'routing_config_test': { password: 'pass1', user_id: 301 },
      'rtt_sender': { password: 'pass1', user_id: 302 },
      'rtt_receiver': { password: 'pass2', user_id: 303 },
      'loss_sender': { password: 'pass1', user_id: 304 },
      'loss_receiver': { password: 'pass2', user_id: 305 },
      'direct_sender': { password: 'pass1', user_id: 306 },
      'direct_receiver': { password: 'pass2', user_id: 307 },
      'tcp_fallback_sender': { password: 'pass1', user_id: 308 },
      'tcp_fallback_receiver': { password: 'pass2', user_id: 309 },
      'route_table_test': { password: 'pass1', user_id: 310 },
      'cross_edge_sender': { password: 'pass1', user_id: 311 },
      'cross_edge_receiver': { password: 'pass2', user_id: 312 },
      'deaf_test_sender': { password: 'pass1', user_id: 313 },
      'deaf_test_deaf': { password: 'pass2', user_id: 314 },
      'deaf_test_normal': { password: 'pass3', user_id: 315 },
      'hub_bypass_sender': { password: 'pass1', user_id: 316 },
      'hub_bypass_receiver': { password: 'pass2', user_id: 317 },
      'relay_compute_user': { password: 'pass1', user_id: 318 },
      'route_push_user': { password: 'pass1', user_id: 319 },
      'relay_sender': { password: 'pass1', user_id: 320 },
      'relay_receiver': { password: 'pass2', user_id: 321 },
      'stress_sender': { password: 'pass1', user_id: 322 },
      'stress_receiver': { password: 'pass2', user_id: 323 },
      'quality_test_e1': { password: 'pass1', user_id: 324 },
      'quality_test_e2': { password: 'pass2', user_id: 325 },
      'quality_test_e3': { password: 'pass3', user_id: 326 },
      'quality_test_e4': { password: 'pass4', user_id: 327 },
      'relay_sender_e1': { password: 'pass1', user_id: 328 },
      'relay_receiver_e4': { password: 'pass2', user_id: 329 },
      'intermediate_e2': { password: 'pass2', user_id: 330 },
      'intermediate_e3': { password: 'pass3', user_id: 331 },
      // 4-Edge test users
      'multi_edge_e1': { password: 'pass1', user_id: 401 },
      'multi_edge_e2': { password: 'pass2', user_id: 402 },
      'multi_edge_e3': { password: 'pass3', user_id: 403 },
      'multi_edge_e4': { password: 'pass4', user_id: 404 },
      'broadcast_sender': { password: 'pass1', user_id: 405 },
      'broadcast_e1': { password: 'pass1', user_id: 406 },
      'broadcast_e2': { password: 'pass2', user_id: 407 },
      'broadcast_e3': { password: 'pass3', user_id: 408 },
      'broadcast_e4': { password: 'pass4', user_id: 409 },
      // Network quality test users
      'degradation_sender': { password: 'pass1', user_id: 501 },
      'degradation_receiver': { password: 'pass2', user_id: 502 },
      'severe_sender': { password: 'pass1', user_id: 503 },
      'severe_receiver': { password: 'pass2', user_id: 504 },
      'recovery_sender': { password: 'pass1', user_id: 505 },
      'recovery_receiver': { password: 'pass2', user_id: 506 },
      // Network simulation test users
      'network_sim_sender': { password: 'pass1', user_id: 507 },
      'network_sim_receiver': { password: 'pass2', user_id: 508 },
      'packet_loss_sender': { password: 'pass1', user_id: 509 },
      'packet_loss_receiver': { password: 'pass2', user_id: 510 },
      'random_payload_user': { password: 'random_pass', user_id: 511 },
      'random_receiver': { password: 'pass1', user_id: 512 },
      // Multi-hop relay test users
      'multi_hop_sender': { password: 'pass1', user_id: 513 },
      'multi_hop_receiver': { password: 'pass2', user_id: 514 },
      'relay_test_e2': { password: 'pass3', user_id: 515 },
      'relay_test_e3': { password: 'pass4', user_id: 516 },
      // Voice test additional users
      'voice_recv_e1_other': { password: 'pass4', user_id: 517 },
      'voice_sender2': { password: 'pass1', user_id: 518 },
      'voice_sender3': { password: 'pass1', user_id: 519 },
      'voice_whisper_sender': { password: 'pass1', user_id: 520 },
      'voice_ch_target_sender': { password: 'pass1', user_id: 521 },
      'voice_loopback_sender': { password: 'pass1', user_id: 522 },
      'voice_multi_sender': { password: 'pass1', user_id: 523 },
      'voice_complex_sender': { password: 'pass1', user_id: 524 },
      // Additional missing voice test users
      'voice_recv_e2_other': { password: 'pass4', user_id: 525 },
      'voice_deaf_e1': { password: 'pass1', user_id: 526 },
      'voice_recv_e1_ch0': { password: 'pass1', user_id: 527 },
      'voice_target1_e1': { password: 'pass1', user_id: 528 },
      'voice_recv_e1_tch1': { password: 'pass1', user_id: 529 },
      'voice_loopback_other': { password: 'pass1', user_id: 530 },
      'voice_multi_recv_e1': { password: 'pass1', user_id: 531 },
      'voice_complex_e1_ch0': { password: 'pass1', user_id: 532 },
      // Additional missing voice test users (edge 2)
      'voice_deaf_e2': { password: 'pass1', user_id: 533 },
      'voice_recv_e2_ch0': { password: 'pass1', user_id: 534 },
      'voice_target1_e2': { password: 'pass1', user_id: 535 },
      'voice_recv_e2_tch1': { password: 'pass1', user_id: 536 },
      'voice_multi_recv_e2': { password: 'pass1', user_id: 537 },
      'voice_complex_e2_ch1': { password: 'pass1', user_id: 538 },
      // TCP voice test users
      'tcp_user': { password: 'tcp_pass', user_id: 601 },
      'tcp_sender': { password: 'tcp_sender_pass', user_id: 602 },
      'tcp_receiver': { password: 'tcp_receiver_pass', user_id: 603 },
      'fallback_user': { password: 'fallback_pass', user_id: 604 },
      'mixed_tcp1': { password: 'password1', user_id: 605 },
      'mixed_tcp2': { password: 'password2', user_id: 606 },
      'mixed_udp': { password: 'password3', user_id: 607 },
      'tcp_to_udp_sender': { password: 'sender_pass', user_id: 608 },
      'tcp_to_udp_receiver': { password: 'receiver_pass', user_id: 609 },
      'udp_to_tcp_sender': { password: 'sender_pass', user_id: 610 },
      'udp_to_tcp_receiver': { password: 'receiver_pass', user_id: 611 },
      'packet_format_user': { password: 'packet_pass', user_id: 612 },
      'cross_edge_tcp1': { password: 'password1', user_id: 613 },
      'cross_edge_tcp2': { password: 'password2', user_id: 614 },
      'perf_test_user': { password: 'perf_pass', user_id: 615 },
      'large_packet_user': { password: 'large_pass', user_id: 616 },
      // Additional missing voice test users (more)
      'voice_normal_e1': { password: 'pass1', user_id: 539 },
      'voice_recv_e1_ch1': { password: 'pass1', user_id: 540 },
      'voice_non_target_e1': { password: 'pass1', user_id: 541 },
      'voice_recv_e1_tch0': { password: 'pass1', user_id: 542 },
      'voice_whisper_tgt_e2': { password: 'pass1', user_id: 543 },
      // Additional missing voice test users (final batch)
      'voice_recv_e2_ch1': { password: 'pass1', user_id: 544 },
      'voice_non_target_e2': { password: 'pass1', user_id: 545 },
      'voice_recv_e1_tch2': { password: 'pass1', user_id: 546 },
      'voice_deaf_e1_ch0': { password: 'pass1', user_id: 547 },
      // Additional missing voice test users (more final)
      'voice_recv_e1_ch2': { password: 'pass1', user_id: 548 },
      'voice_normal_e1_ch2': { password: 'pass1', user_id: 549 },
      // UDP connection test users
      'tcp_fallback_user': { password: 'password123', user_id: 550 },
      'udp_ping_test': { password: 'password123', user_id: 551 },
      'udp_multi_sender': { password: 'password123', user_id: 552 },
      'udp_multi_receiver': { password: 'password123', user_id: 553 },
      // Voice target permission test users
      'sender_allowed': { password: 'sender_allowed_pass', user_id: 719 },
      'target_user_allowed': { password: 'target_allowed_pass', user_id: 720 },
      'whisper_allowed': { password: 'whisper_pass', user_id: 701 },
      'target_user': { password: 'target_pass', user_id: 702 },
      'no_whisper_user': { password: 'no_whisper_pass', user_id: 703 },
      'target_user2': { password: 'target_pass2', user_id: 704 },
      'sender_user': { password: 'sender_pass', user_id: 705 },
      'receiver_in_channel': { password: 'receiver_pass', user_id: 706 },
      'restricted_sender': { password: 'restricted_pass', user_id: 707 },
      'sender_visible': { password: 'sender_visible_pass', user_id: 708 },
      'target_visible': { password: 'target_visible_pass', user_id: 709 },
      'sender_invalid': { password: 'sender_invalid_pass', user_id: 710 },
      'remover': { password: 'remover_pass', user_id: 711 },
      'target_edge2': { password: 'target_edge2_pass', user_id: 713 },
      'multi_sender': { password: 'multi_sender_pass', user_id: 714 },
      'target1': { password: 'target1_pass', user_id: 715 },
      'target2': { password: 'target2_pass', user_id: 716 },
      'partial_sender': { password: 'partial_sender_pass', user_id: 717 },
      'accessible_target': { password: 'accessible_target_pass', user_id: 718 },
      // ACL actual operation test users
      'acl_op_user': { password: 'acl_op_pass', user_id: 750, groups: ['acl_testers'] },
      'acl_op_observer': { password: 'acl_op_obs_pass', user_id: 751, groups: ['acl_testers'] },
      // Channel Linking test users
      'voice_recv_e2_ch2': { password: 'pass1', user_id: 760 },
      'chain_a_e1': { password: 'pass1', user_id: 761 },
      'chain_b_e1': { password: 'pass1', user_id: 762 },
      'chain_b_e2': { password: 'pass1', user_id: 763 },
      'chain_c_e1': { password: 'pass1', user_id: 764 },
      'chain_c_e2': { password: 'pass1', user_id: 765 },
      // Hub restart channel linking test users
      'restart_ch0_e1': { password: 'pass1', user_id: 766 },
      'restart_ch1_e1': { password: 'pass1', user_id: 767 },
      // Voice-after-channel-move test users
      'ch_move_sender': { password: 'pass1', user_id: 801 },
      'ch_move_receiver': { password: 'pass2', user_id: 802 },
      'ch_move_admin': { password: 'admin123', user_id: 803, groups: ['admin'] },
      'ch_move_target': { password: 'pass3', user_id: 804 },
    };